---
- name: Transfer the consul-template systemd service unit file
  copy:
    src: consul-template@.service
    dest: /etc/systemd/system/consul-template@.service

- name: Ensure the consul-template group exists
  group:
    name: "{{ consul_template_group }}"
    state: present

- name: Ensure the consul-template user exists
  user:
    name: "{{ consul_template_user }}"
    home: "{{ consul_template_directory }}"
    groups: "{{ consul_template_group }}"
    append: yes
    shell: /sbin/nologin
    system: yes
    state: present

- name: Ensure the consul-template directory exists with correct permissions
  file:
    path: "{{ consul_template_directory }}"
    state: directory
    owner: "{{ consul_template_user }}"
    group: "{{ consul_template_group }}"
...
