---
- name: Transfer the consul-template systemd service unit file
  template:
    src: consul-template@.service.j2
    dest: /etc/systemd/system/consul-template@.service

- name: Ensure the consul-template group exists
  group:
    name: "{{ ctpl_group }}"
    state: present
  when: ctpl_configure_user

- name: Ensure the consul-template user exists
  user:
    name: "{{ ctpl_user }}"
    home: "{{ ctpl_directory }}"
    groups: "{{ ctpl_group }}"
    append: yes
    shell: /sbin/nologin
    system: yes
    state: present
  when: ctpl_configure_user

- name: Ensure the consul-template directory exists
  file:
    path: "{{ ctpl_directory }}"
    state: directory

- name: Ensure the consul-template directory exists with correct permissions
  file:
    path: "{{ ctpl_directory }}"
    state: directory
    owner: "{{ ctpl_user }}"
    group: "{{ ctpl_group }}"
  when: ctpl_configure_user
...
