---
- name: Download and unzip the consul-template archive
  unarchive:
    src: "https://releases.hashicorp.com/consul-template/{{ ctpl_version }}/consul-template_{{ ctpl_version }}_linux_amd64.zip"
    dest: /tmp
    remote_src: yes
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Copy across the consul-template binary
  copy:
    src: /tmp/consul-template
    dest: /usr/local/bin/consul-template
    mode: '0755'
    owner: root
    group: root
...
